import { Role } from '../../types/user';

export const ACCESS_ROLES = {
  AAPEN_STATISTIKK: [],
  TOTALSTATISTIKK: [Role.ROLE_KLAGEINSTANS_ALLE, Role.ROLE_KLAGE_SAKSBEHANDLER, Role.ROLE_KLAGE_LEDER],
  LEDERSTATISTIKK: [Role.ROLE_KLAGE_LEDER],
  KVALITETSVURDERINGER: [Role.ROLE_KLAGEINSTANS_ALLE, Role.ROLE_KLAGE_SAKSBEHANDLER],
  TILBAKEMELDINGER: [Role.ROLE_VEDTAKSINSTANS_LEDER],
  MIN_STATISTIKK: [Role.ROLE_KLAGEINSTANS_ALLE, Role.ROLE_KLAGE_SAKSBEHANDLER],
};
