import { Role } from '../../types/user';

export const ACCESS_ROLES = {
  AAPEN_STATISTIKK: [],
  TOTALSTATISTIKK: [Role.ROLE_KLAGE_SAKSBEHANDLER, Role.ROLE_KLAGE_LEDER, Role.ROLE_KLAGE_FAGANSVARLIG],
  LEDERSTATISTIKK: [Role.ROLE_KLAGE_LEDER],
  KVALITETSREGISTRERINGER: [Role.ROLE_KLAGE_SAKSBEHANDLER],
  TILBAKEMELDINGER: [Role.ROLE_VEDTAKSINSTANS_LEDER],
};
