import type { IKodeverkSimpleValue } from './kodeverk';

interface Navn {
  fornavn?: string;
  etternavn?: string;
  sammensattNavn?: string;
}

export interface IUser {
  ident: string;
  navn: Navn;
  roller: Role[];
  ansattEnhet: IKodeverkSimpleValue;
}

export enum Role {
  KAKA_KVALITETSVURDERING = 'KAKA_KVALITETSVURDERING',
  KAKA_TOTALSTATISTIKK = 'KAKA_TOTALSTATISTIKK',
  KAKA_LEDERSTATISTIKK = 'KAKA_LEDERSTATISTIKK',
  KAKA_KVALITETSTILBAKEMELDINGER = 'KAKA_KVALITETSTILBAKEMELDINGER',
  EGEN_ANSATT = 'EGEN_ANSATT',
  FORTROLIG = 'FORTROLIG',
  STRENGT_FORTROLIG = 'STRENGT_FORTROLIG',
  KAKA_EXCEL_UTTREKK_MED_FRITEKST = 'KAKA_EXCEL_UTTREKK_MED_FRITEKST',
  KAKA_EXCEL_UTTREKK_UTEN_FRITEKST = 'KAKA_EXCEL_UTTREKK_UTEN_FRITEKST',
  KAKA_ADMIN = 'KAKA_ADMIN',
}
