export enum QueryParams {
  ENHETER = 'enheter',
  KLAGEENHETER = 'klageenheter',
  TYPES = 'types',
  YTELSER = 'ytelser',
  UTFALL = 'utfall',
  YEAR = 'year',
  FROM_MONTH = 'fromMonth',
  TO_MONTH = 'toMonth',
  FROM_DATE = 'fromDate',
  TO_DATE = 'toDate',
  HJEMLER = 'hjemler',
  BEHANDLINGSTID = 'bht',
  KVALITETSVURDERING = 'kvt',
  SAKSBEHANDLERE = 'saksbehandlere',
  MANGELFULLT = 'mangelfullt',
  KOMMENTARER = 'kommentarer',
  VEDTAKSINSTANSGRUPPER = 'vedtaksinstansgrupper',
  TILBAKEKREVING = 'tilbakekreving',
}
