apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: kaka-frontend
  namespace: klage
  labels:
    team: klage
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "86400"
spec:
  image: {{image}}
  replicas:
    min: 2
    max: 3
  azure:
    application:
      enabled: true
      tenant: {{tenant}}
      allowAllUsers: true
      claims:
        extra:
          - NAVident
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths: 
        - /isAlive
        - /isReady
        - /version
        - /assets/*
        - /favicon/*
        - /site.webmanifest
        - /*.js
        - /*.js.map
        - /*.html
        - /*.txt
        - /*.css
        - /*.ico
        - /*.png
  prometheus:
    enabled: true
    path: /metrics
  accessPolicy:
    outbound:
      rules:
        - application: kaka-api
        - application: klage-kodeverk-api
      external:
        - host: login.microsoftonline.com
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  envFrom:
    - secret: slack-url
  liveness:
    path: /isAlive
    initialDelay: 3
    periodSeconds: 1
    timeout: 1
    failureThreshold: 10
  readiness:
    path: /isReady
    initialDelay: 3
    periodSeconds: 1
    timeout: 1
    failureThreshold: 10
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
