apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: kaka-frontend
  namespace: klage
  labels:
    team: klage
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    #nais.io/restricted: "true"
spec:
  image: {{image}}
  replicas:
    min: 2
    max: 3
  azure:
    application:
      enabled: true

  accessPolicy:
    outbound:
      rules:
        - application: kaka-redis-fe
        - application: kaka-api
          cluster: prod-gcp
          namespace: klage
      external:
        - host: login.microsoftonline.com
        - host: kaka-api.intern.nav.no
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  envFrom:
    - secret: kabal-session-key
    - secret: slack-url
