name: Deploy branch to dev (manual)

on:
  workflow_dispatch:

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/kaka-frontend:${{ github.sha }}
jobs:
  deploytodev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci
      - name: Build frontend
        run: |
          cd frontend
          npm run build
      - name: Test frontend
        run: |
          cd frontend
          npm test
      - name: Install server dependencies
        run: |
          cd server
          npm ci
      - name: Build server
        run: |
          cd server
          npm run build
      - name: Test server
        run: |
          cd server
          npm test
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SESSION_KEY: ${{ secrets.klage-session-key }}
        run: |
          cat Dockerfile
          docker build --tag ${IMAGE} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}
      - uses: actions/checkout@v2
        name: Checkout code
      - uses: nais/deploy/actions/deploy@master
        env:
          SESSION_KEY: ${{ secrets.klage-session-key }}
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/dev.yaml
          VARS: nais/vars.yaml
